# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UCLA CDL
# email: emjun(at)cs(dot)ucla(dot)edu
# description: >- # this means to ignore newlines until "baseurl:"
#   Eunice M. Jun researches how to enable anyone to use technology and data
#   effectively to learn and make informed decisions that advance society.

# baseurl: "" # the subpath of your site, e.g. /blog
url: "ucla-cdl.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: eunicemjun
# github_username:  emjun

# Build settings
theme: minima
plugins:
  - jekyll-scholar
scholar:
  source: ./_bibliography
  bibliography: papers.bib #, others.bib
  bibliography_template: bibtemplate
  repository: 'assets/files'
  
  sort_by: year, order
  order: descending, ascending
  
  replace_strings: true
  query: "@*"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# colorize code snippets with the pygments module
highlighter: rouge


# Base pathname for links.
base: ''

# Navigation bar links.
# navigation:
#   - title: Home
#     link: /
#   - title: Publications
#     link: /publications.html
#   - title: Software
#     link: /software
#   - title: CV
#     link: /cv.html


# Google fonts
# <link rel="preconnect" href="https://fonts.googleapis.com">
# <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
# <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet"> 